### ISSUE TITLE
Benchmark Presto

### ISSUE THREAD

**Issue by LaertNuhu** [LaertNuhu/federated_queries_benchmark#6]
1. Which tpch queries will be tested?
2. Clusted vs single node?
3. Data sources on different machines
4. Differences between data scources:
- Postgres (default)
- Mariadb
- MySQL

--- 
2 -> Setup only on single node.

**Comment by LaertNuhu** [comment]
@bithianjuman 
afce9ca82c9fb5dac1d2983039747d0a458e4166
General benchmarking function created. Average query time is returned.
Which queries are to be benchmarked and what other metrics are interesting need to be discussed.

**Comment by bithianjuman** [comment]
we can discuss it today after meeting with Harry.
